feat: 포트폴리오 CRUD API (공작소 양식) 개발
Gongjakso/server pull request #198
Opened 2024-09-05 16:44 UTC by jinnxyoung

## #️⃣ 연관된 이슈
> #197 

## 📝 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 공작소 내부 양식 포트폴리오 CRUD  API 개발

확인사항
- 아직 인증정보를 가져오는 부분은 구현하지 못했습니다. 차주 진행하여 업데이트 될 예정입니다.
- 포트폴리오 외부 형식(내 파일 업로드)은 동일 혹은 비슷한 로직으로 금주부터 차주까지 진행하면서 빠르게 업데이트 될 예정입니다.

### 스크린샷 (선택)
<img width="1514" alt="스크린샷 2024-09-05 23 55 01" src="https://github.com/user-attachments/assets/a46f5ee9-8cad-4623-8b82-49d8bd66692e">
<img width="1514" alt="스크린샷 2024-09-05 23 55 21" src="https://github.com/user-attachments/assets/e6b4a797-b23f-4759-bc29-bdb852e444a7">
<img width="1514" alt="스크린샷 2024-09-05 23 55 49" src="https://github.com/user-attachments/assets/65773be9-1a06-43e1-9f92-b5c92eac1c1f">
<img width="1514" alt="스크린샷 2024-09-05 23 56 03" src="https://github.com/user-attachments/assets/8be0fc7a-9239-458f-b1a8-1332cdafc807">

## 💬 리뷰 요구사항(선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
> Ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
1. Json List 저장 방식 및 record 사용이 익숙치 않아 적용하면서도 간간히 헤맨 감이 없지 않아 있었습니다. 😂
클린코드에 잘 작성이 됐을까 모르겠네요. 🥹
2. Json 타입과 Text 타입 중 어느 상황에서 적절하게 선택하여 사용하는 것이 좋은지 고민이 됩니다.
3. List <Map<String, Obejct>> 자료형 사용을 상황에 따라 더 권장하는 것 같기도 한데, 어떻게 생각하시나요? 이 부분 의견 나누고 싶습니다. 현재 Map<String, Obejct> 자료형 사용이 더 좋은 선택이라면 의견 나누고 공부도 한 후, 추후 업데이트 해보도록 하겠습니다.
4. update 로직이 더 간결하게 될 순 없었을까.. 라는 생각이 드네요. null 여부를 적용하다 보니 그냥 register 로직과 동일한 느낌이라.. 피드백 주시면 감사하겠습니다!
5. 현재 DB portfolio 테이블이 테스트 과정에서 데이터가 8월 생성 게시물부터 다수 들어가 있습니다. 한번 다 날리실 계획 있으신지..💣

2024-09-06 00:03 UTC, dl-00-e8 commented
파일 업로드 같은 경우, Presigned-url을 적용할 예정이라 지금 작업 완료되면 제가 바로 진행하면 될 것 같아요. Presigned-url 해보고 싶으시면, 제가 옆에서 도와드릴게요!

2024-09-06 00:04 UTC, dl-00-e8 commented
5번 내용은 저희 실제DB에 데이터가 적재가 안 되었을 건데, 어떤 내용인지 다시 설명해주실 수 있을까요?

2024-09-06 03:21 UTC, yumzen commented on src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
생성, 수정 메소드에 `portfolioData` 객체 생성하는 과정에서 중복되는 코드가 있는 것 같은데 하나의 메소드로 정리해서 사용하면 어떨까요???

2024-09-06 08:18 UTC, dl-00-e8 requested changes
변경 요청 사항 확인 및 코멘트 부탁드립니다!

2024-09-06 08:18 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
> +    public ApplicationResponse<Portfolio> searchPortfolio(@PathVariable("portfolio_id") Long portfolioId) {
포트폴리오 상세 조회가 search라는 메소드로 명명되면, 혼란이 있을 것 같아요. getPortfolio와 같은 네이밍은 어떤가요?

2024-09-06 08:18 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/dto/request/PortfolioReq.java
추후에, `@Schema` 활용해서 Swagger 예시 추가해주시면 좋을 것 같아요.

2024-09-06 08:18 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
> +        PortfolioRes portfolioRes = PortfolioRes.from(updatedPortfolio);
DTO Convert를 Controller 계층에서 구현하신 이유를 알 수 있을까요?

2024-09-06 08:18 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
> +    public ApplicationResponse<Portfolio> registerPortfolio(@Valid @RequestBody PortfolioReq portfolioReq) {
`PortfolioRes`라는 응답 DTO를 정의했지만, 여기서 Entity를 그대로 반환하는 이유가 있을까요? 필요없는 정보까지 반환할 수 있으니 변경하는 게 낫지 않을까요?

2024-09-06 08:18 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
> +    public Portfolio registerPortfolio(PortfolioReq portfolioReq) {
`PortofolioReq`를 `Portfolio`로 변환할 때, record를 각각 변환하기보단 하나의 메소드로 묶어서 분리하는 것은 어떤가요?

2024-09-06 08:18 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 ID를 가진 포트폴리오가 없습니다. : " + portfolioId));
`ApplicatiaonException`을 정의해놨는데, 이렇게 String으로 쓰게 된다면 혼란이 있을 것 같아요.  저희가 정의한 `ApplicationException`으로 변경하는 게 더 좋아보여요!

2024-09-07 06:49 UTC, jinnxyoung commented
> 파일 업로드 같은 경우, Presigned-url을 적용할 예정이라 지금 작업 완료되면 제가 바로 진행하면 될 것 같아요. Presigned-url 해보고 싶으시면, 제가 옆에서 도와드릴게요!

좋습니다! 한번 해보고 싶습니다. :) 관련해서 내용 한번 찾아보도록 할게요! 제가 어느 부분을 집중적으로 보면 좋을지 추천해주시면 감사하겠습니다!

> 5번 내용은 저희 실제DB에 데이터가 적재가 안 되었을 건데, 어떤 내용인지 다시 설명해주실 수 있을까요?

제가 다시 확인해본 결과, 말씀주신 대로 실서버 DB에는 반영되지 않고 제 로컬 환경 DB에만 테스트로 적재된 것을 확인했습니다. auto-ddl validate 옵션을 확인하는 것을 깜빡해 착각했습니다. 😂

더불어 세부적으로 리뷰해주신 내용 다 확인하였습니다. 주말내로 최대한 해결하고 늦어도 차주 월요일 중으로는 업데이트해 다시 PR 올리도록 하겠습니다! 감사합니다. 😊

2024-09-09 04:00 UTC, yumzen approved these changes
고생하셨습니다!

2024-09-09 04:03 UTC, dl-00-e8 reviewed
리뷰 하나 추가했습니다. 해당 부분 확인하시고 변경 또는 답변 주시면, Approve 할게요!

2024-09-09 04:03 UTC, dl-00-e8 commented on src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
> +    @Transactional
읽기 메소드에서, `@Transactional`은 없어도 되지 않을까요? 클래스 전체로 읽기 전용 트랜잭션이 걸려있어서 여쭤보아요!

2024-09-09 05:54 UTC, jinnxyoung commented on src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
> +    @Transactional
네 맞아요! 미처 확인하지 못했네요. 😂 수정사항 반영하였습니다!

2024-09-11 05:05 UTC, dl-00-e8 approved these changes
고생 많으셨습니다!

2024-09-12 06:07 UTC, merged